### ISSUE TITLE
Transfer fails

### ISSUE THREAD

**Issue by hemantxpatel** [eclipse-tractusx/tutorial-resources#231]
### Current Behavior

Transfer doesn't complete.

### Expected Behavior

Transfer should be completed successfully.

### Steps To Reproduce

- Initiate negotiation.
- Validate Negotiation state `FINALIZED`.
- Initiate transfer.
- Check Transfer State.

Related to: eclipse-edc/Connector#3810

### Possible Fix
- Generate a private / public key pair and store it in connector's vault.
- Define vault keys as connector config. Check config details [here](https://github.com/eclipse-edc/Connector/tree/main/extensions/control-plane/transfer/transfer-data-plane).

**Comment by oliverbusch** [comment]
The fix solves not the complete problem see [(https://github.com/eclipse-tractusx/tutorial-resources/pull/232#issuecomment-1932036523)](https://github.com/eclipse-tractusx/tutorial-resources/pull/232#issuecomment-1932036523).  It looks like that the created token has an invalid signature.
