### ISSUE TITLE
Broken link in EDR tutorial

### ISSUE THREAD

**Issue by anschl** [eclipse-tractusx/tutorial-resources#234]
https://github.com/eclipse-tractusx/tutorial-resources/blob/ef6f2a7664ca480a053b49b7e23f0eef8e6e21c9/mxd/docs/EDR%20Transfer%20Tutorial.md

The first link is broken and I can't find the file it linked to.

Thanks!

**Comment by hemantxpatel** [comment]
Related to eclipse-tractusx/tractusx-edc#1097
