### ISSUE TITLE
EDC doesn't come up with terraform

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/tutorial-resources#257]
### Current Behavior

I tried to deploy (local) the MXD as described in the [tutorial](https://eclipse-tractusx.github.io/docs/tutorials/e2e/connect/deployComponents) (basically the same as in your readme here). Everything went fine. But `terraform apply` doesn't work.

Both control planes dont start
![image](https://github.com/eclipse-tractusx/tutorial-resources/assets/84396022/4b002903-a9b4-484d-9673-9be9cbbe6547)

For the pod logs, you can find more information
![image](https://github.com/eclipse-tractusx/tutorial-resources/assets/84396022/6ef36bfa-38bc-4e17-81a1-af79f7ff371a)

### Expected Behavior

Both control planes should come up :) @paullatzelsperger already provided an interim fix for this problem, but its just a local fix and needs to be adapted here in this repository. main.tf file

![image](https://github.com/eclipse-tractusx/tutorial-resources/assets/84396022/62816b46-7774-4f67-aa50-b96900ceeb7c)

### Steps To Reproduce

Just follow the tutorial, or the readme within in the MXD folder. What i additional did, I changed the uses EDC Version (control plane and data plane) to version 0.5.3 instead of the latest.

**Comment by paullatzelsperger** [comment]
further info: the version of (upstream) EDC that is used in T-X EDC 0.5.3 cannot handle EDDSA keys, only ECDSA keys using the P256 Curve. That's why that blows up.

**Comment by hemantxpatel** [comment]
So should we switch to `ECDSA` alg in place of `ED25519`.
Right now MXD is running with `0.6.0`.

**Comment by hemantxpatel** [comment]
@stephanbcbauer , we already have a `0.7.x` release. Do you think we should switch the algorithm compatible with old version `0.5.3`.
