### ISSUE TITLE
Get Asset Data via Consumer Proxy Request fails 

### ISSUE THREAD

**Issue by hemantxpatel** [eclipse-tractusx/tutorial-resources#267]
### Current Behavior

Proxy call to consumer dataplane fails, as consumer dataplane tries to reach out to the provider's public url `http://localhost/alice/api/public` which doesn't exist.
```shell
curl --location 'http://localhost/bob/proxy/aas/request' \
--header 'Content-Type: application/json' \
--header 'X-Api-Key: password' \
--data '{
    "assetId": "1",
    "providerId": "BPNL000000000001"
}'
```
Above curl returns
```
'java.net.ConnectException: Failed to connect to localhost/[
  0: 0: 0: 0: 0: 0: 0: 1
]: 80'
```

### Expected Behavior

Consumer Proxy Url should return the asset data.

### Steps To Reproduce

- Initiate an EDR Negotiation
- Make above Proxy Request

### Cause
This PR #233 adds the local ingress url as dataplane public url, due to this an EDR Response looks like this.
```
{
  "@type": "DataAddress",
  "type": "EDR",
  "authCode": "auth code",
  "endpoint": "http://localhost/alice/api/public",
  "id": "2a17a657-479a-454c-ab42-52078c2824b8",
  "authKey": "Authorization",
  "@context": {}
}
``` 
When Consumer Dataplane tries to reach out to the provider's public url `http://localhost/alice/api/public`, it fails.

### Proposed Solution
PR #233 should be reverted.

**Comment by hemantxpatel** [comment]
@paullatzelsperger Could you please have a look and let us know how to proceed.

**Comment by ndr-brt** [comment]
consumer control plane in fact is not part the flow for a long time now, in a transfer scenario, only a provider data plane is needed

**Comment by hemantxpatel** [comment]
> consumer control plane in fact is not part of the flow for a long time now, in a transfer scenario, only a provider data plane is needed  

Yes, Urls `http://localhost/bob/proxy/aas/request`, `http://localhost/alice/api/public` routed to data plane instances.

**Comment by hemantxpatel** [comment]
An issue was reported #279 as well.
Will revert the changes in the PR #233 to fix this.

@ndr-brt let me know if you think otherwise.
