### ISSUE TITLE
Outdated Policies in Policy Playground

### ISSUE THREAD

**Issue by mhellmeier** [eclipse-tractusx/tutorial-resources#329]
### Current Behavior

The current policy playground is able to generate policies.

Code:
https://github.com/eclipse-tractusx/tutorial-resources/tree/main/edc-policy-playground

Hosted Version:
https://eclipse-tractusx.github.io/tutorial-resources/policy-playground/

The generated policies are outdated and not in line with the latest Tractus-X EDC version. Further, they aren't fully valid JSON-LD.

### Expected Behavior

Provided policies should be in line with the latest ODRL profile, reference implementations, and standards.

**Comment by wolf4ood** [comment]
Hi @mhellmeier 


thanks for raising this, we have planned the work on upgrading the policies compatible with the latest tx-edc version, but i would not label this as a bug.

**Comment by mhellmeier** [comment]
IMHO, the currently generated policies are wrong, incompatible, and don't work. Therefore, it is a bug.
