### ISSUE TITLE
seed-connectors fails

### ISSUE THREAD

**Issue by Moritz72** [eclipse-tractusx/tutorial-resources#387]
### Current Behavior
When starting up the MXD one gets
```
╷
│ Error: job: default/seed-connectors is not in complete state
│ 
│   with kubernetes_job.seed_connectors_via_mgmt_api,
│   on seed_data.tf line 24, in resource "kubernetes_job" "seed_connectors_via_mgmt_api":
│   24: resource "kubernetes_job" "seed_connectors_via_mgmt_api" {
│ 
╵
```

This is likely because the [MIW](https://github.com/eclipse-tractusx/managed-identity-wallet) got a new version and should be fixed by pinning the version of the MIW as was done with the tractusx-edc. Specifically by changing
```
image             = "tractusx/managed-identity-wallet:main"
```
to
```
image             = "tractusx/managed-identity-wallet:0.4.0"
```
in miw.tf.

### Expected Behavior

There is no error when starting up the MXD.

### Steps To Reproduce

Start up the MXD as described in the README.

**Comment by hemantxpatel** [comment]
Thanks for the report, we will pin the correct version to MIW.
