### ISSUE TITLE
CI: improve the MXD test

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-tractusx/tutorial-resources#43]
### WHAT

Currently, during CI runs, we only test that both `bob` and `alice` are up and running, check out [this workflow job](https://github.com/eclipse-tractusx/tutorial-resources/blob/c140d461667d640cab27c27983283a5eddafea81/.github/workflows/run-terraform.yml#L70). That is not very thorough and we should improve it. 

At least the following aspects should be tested:
- create an asset, policy, contract def
- make a catalog request (bob -> alice, alice -> bob)
- [optional] perform contract negotiation
- [optional] perform data transfer

For that, we could use another postman collection and leverage the test feature, or even just plain `curl` commands.

## WHY
Testing should be improved, MXD does indeed serve as a testing ground of sorts.

**Comment by ravinderkumarsap** [comment]
While working on improve the MXD test we have identified the two approaches 

1.  Run Testes using CURL Commands
2.  Run Testes Json collection Using Newman (https://github.com/postmanlabs/newman)

Which one is more preferable so that we can implement the same @paullatzelsperger
