### ISSUE TITLE
Docs: Enrich tutorial section 3. Add some data

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-tractusx/tutorial-resources#61]

**Comment by moiarayam** [comment]
Hi there,

are there any commits on your fork on this issue? Otherwise I can try it during the next days and ask for your help if necessary.

**Comment by hemantxpatel** [comment]
Hi @moiarayam , we may not need this.
Earlier plan was to add all tutorials in the readme, but now we have splitted tutorials in multiple files. Once other tutorials are complete, we will cleanup the main readme.

@wolf4ood you may close this issue.
