### ISSUE TITLE
MXD: MIW responded with a 404

### ISSUE THREAD

**Issue by hamidonos** [eclipse-tractusx/tutorial-resources#72]
MIW not working after running the MXD terraform installation
MIW responds with 404
No error logs generated on MIW side
Error seems not to happen on every installation

![image](https://github.com/eclipse-tractusx/tractusx-edc/assets/94196804/16d0ed23-f72a-4317-a7ef-94ea2e2f9633)

OS: Mac OS M1

After manually redeploying MIW module everything worked
_terraform taint kubernetes_deployment.miw_

**Comment by hamidonos** [comment]
Hi @wolf4ood 

yeah you're right, thx for moving it :) 

Yes, i got that on first installation(s).

**Comment by wolf4ood** [comment]
you have to check if on first installation the miw seeds job runs, it could be that problem

**Comment by hamidonos** [comment]
you could be right but isn't that error message still misleading?

**Comment by wolf4ood** [comment]
the 404 it's ok means that for the configured BPN talking with the MIW the wallet is not available

**Comment by hamidonos** [comment]
the seed job ran through on the first installtion
had to manually kill the miw and restart the seed job

**Comment by wolf4ood** [comment]
also if you check the connector logs in this case you should see a detailed version of the 404, something like 

```
MIW API returned 404 with body: {"type":"about:blank","title":"Wallet not found for identifier BPNL000000000002","status":404,"detail":"Wallet not found for identifier BPNL000000000002","instance":"/api/credentials","properties":{"timestamp":1695025380738}}

```

**Comment by hemantxpatel** [comment]
It could be just one occurrence. I haven't observed it. I am going to close it. Feel free to reopen / open a new issue, if you find it again.
